name: Build Release Branch Nightly for TestPyPI

on:
  schedule:
    # Run from April 8th to April 13th at 02:00 UTC (10:00 PM EDT)
    - cron: "0 2 8-13 4 *"
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  setup:
    name: Setup the release
    runs-on: ubuntu-22.04
    outputs:
      branch: v0.11.0-rc
    steps:
    - name: Checkout Catalyst repo release branch
      uses: actions/checkout@v4
      with:
        ref: v0.11.0-rc
        ssh-key: ${{ secrets.NIGHTLY_VERSION_UPDATE_DEPLOY_KEY }}

    - name: Bump RC version
      run: |
        python $GITHUB_WORKSPACE/.github/workflows/set_rc_version.py

  # Only build the most popular configurations on a nightly schedule to save PyPI storage.

  linux-x86:
    name: Build on Linux x86-64
    needs: [setup]
    uses: ./.github/workflows/build-wheel-linux-x86_64.yaml
    with:
      branch: v0.11.0-rc

  linux-aarch:
    name: Build on Linux aarch64
    needs: [setup]
    uses: ./.github/workflows/build-wheel-linux-arm64.yaml
    with:
      branch: v0.11.0-rc

  macos-arm:
    name: Build on macOS arm64
    needs: [setup]
    uses: ./.github/workflows/build-wheel-macos-arm64.yaml
    with:
      branch: v0.11.0-rc
